import { Link } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { schoolApi } from "../../api/school";
import { useAuthStore } from "../../store/authStore";
import { ErrorState, LoadingState, PageHeader } from "../../components/ui/Page";
import { formatDate } from "../../lib/format";

const today = new Date().toISOString().slice(0, 10);
export function DashboardPage() {
  const user = useAuthStore((state) => state.user);
  const substitutions = useQuery({ queryKey: ["substitutions", "today"], queryFn: () => schoolApi.substitutions({ date_from: today, date_to: today }) });
  const events = useQuery({ queryKey: ["events", "upcoming"], queryFn: () => schoolApi.events({ start_date: today }) });
  const salutation = new Intl.DateTimeFormat("de-DE", { weekday: "long", day: "numeric", month: "long" }).format(new Date());
  return <div className="page"><PageHeader eyebrow={salutation} title={`Hallo, ${user?.first_name ?? ""}.`} />
    {substitutions.isLoading || events.isLoading ? <LoadingState /> : substitutions.isError || events.isError ? <ErrorState onRetry={() => { substitutions.refetch(); events.refetch(); }} /> : <><section className="dashboard-hero"><div><p className="eyebrow text-indigo-100">Dein Schultag</p><h2>Alles, was heute wichtig ist — an einem ruhigen Ort.</h2><p>{substitutions.data?.length ? `${substitutions.data.length} Änderungen im Unterricht brauchen deine Aufmerksamkeit.` : "Dein Stundenplan ist heute unverändert."}</p></div><Link to="/substitutions" className="hero-link">Tagesplan öffnen <span>→</span></Link></section><div className="mt-5 grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><section className="surface overflow-hidden"><div className="flex items-center justify-between border-b border-gray-100 px-5 py-4"><h2>Heute im Plan</h2><Link className="text-button" to="/substitutions">Alle anzeigen</Link></div>{substitutions.data?.length ? substitutions.data.map((item) => <div className="data-row" key={item.id}><span className="grid size-9 place-items-center rounded-lg bg-indigo-50 font-bold text-indigo-700">{item.period}.</span><div className="data-row-main"><strong>{item.type === "cancellation" ? "Unterricht entfällt" : "Unterricht wurde geändert"}</strong><p>{item.room ? `Raum ${item.room}` : "Details im Vertretungsplan"}{item.note ? ` · ${item.note}` : ""}</p></div><span className={`pill ${item.type === "cancellation" ? "red" : "blue"}`}>{item.type === "cancellation" ? "Entfall" : "Neu"}</span></div>) : <div className="px-5 py-9 text-sm text-gray-500">Heute sind keine Vertretungen oder Raumwechsel eingetragen.</div>}</section><section className="surface overflow-hidden"><div className="flex items-center justify-between border-b border-gray-100 px-5 py-4"><h2>Nächste Termine</h2><Link className="text-button" to="/calendar">Kalender</Link></div>{events.data?.slice().sort((a,b) => a.start_time.localeCompare(b.start_time)).slice(0,4).map((event) => <div className="data-row" key={event.id}><time className="w-12 font-mono text-xs text-gray-500">{formatDate(event.start_time)}</time><div className="data-row-main"><strong>{event.title}</strong><p>{event.all_day ? "Ganztägig" : new Date(event.start_time).toLocaleTimeString("de-DE", {hour:"2-digit",minute:"2-digit"})}</p></div></div>) || null}{!events.data?.length && <div className="px-5 py-9 text-sm text-gray-500">Der Kalender ist für die nächsten Tage frei.</div>}</section></div></>}
  </div>;
}
