---
- name: Ensure app directory exists
  file:
    path: "{{ app_path }}"
    state: directory

- name: Pull latest code (safe mode)
  command: git pull origin main
  args:
    chdir: /opt/check24app

- name: Clean webroot
  file:
    path: /var/www/mysite
    state: absent

- name: Recreate webroot
  file:
    path: /var/www/mysite
    state: directory
    owner: caddy
    group: caddy
    mode: "0755"

- name: Copy React app (static files)
  copy:
    src: "{{ app_path }}/{{ app_folder }}/"
    dest: /var/www/mysite/
    remote_src: yes

- name: Set permissions
  file:
    path: /var/www/mysite
    owner: caddy
    group: caddy
    recurse: yes

- name: Reload Caddy
  systemd:
    name: caddy
    state: reloaded