---
- name: Deploy React App to Caddy
  hosts: webservers
  become: true

  vars:
    repo_url: "https://github.com/Christoph3573/Check24Projekt"
    app_path: "/opt/check24app"
    app_folder: "session-04-React-App"

  roles:
    - caddy
    - ssh_tunnel
    - react_deploy